from typing import Type, Iterable, Sized, Iterator, NewType

"""
The type which generated by 
google.protobuf.reflection.GeneratedProtocolMessageType
"""
GeneratedProtocolMessageType = "GeneratedProtocolMessageType"


class ProtoList(Sized, Iterable):

    def __init__(self, path, proto_class: Type[GeneratedProtocolMessageType]):
        self.path = path
        self.proto_class = proto_class

    def __enter__(self):
        pass  # TODO(Assignment 8)

    def __exit__(self, exc_type, exc_val, exc_tb):
        pass  # TODO(Assignment 8)

    def __len__(self):
        pass  # TODO(Assignment 8)

    def __getitem__(self, item):
        pass  # TODO(Assignment 8)

    def __iter__(self) -> Iterator[GeneratedProtocolMessageType]:
        pass  # TODO(Assignment 8)




