from typing import Type, Iterable, Sized, Iterator, NewType
from google.protobuf.reflection import GeneratedProtocolMessageType

"""
The type which generated by 
google.protobuf.reflection.GeneratedProtocolMessageType
"""
GeneratedProtocolMessageType = "GeneratedProtocolMessageType"


class ProtoList(Sized, Iterable):

    def __init__(self, path, proto_class: Type[GeneratedProtocolMessageType]):
        self.path = path
        self.proto_class = proto_class

    def __enter__(self):
        self.file = open(self.path, 'rb')
        self.lengths = list()
        self.coordinates = list()
        while (N := self.file.read(8)) != b'':
            self.lengths.append(self.file.tell())
            N = int.from_bytes(N, byteorder='big')
            self.coordinates.append(N)
            self.file.seek(N, 1)
        return self

    def __exit__(self, _type, value, tb):
        self.file.__exit__(_type, value, tb)

    def __len__(self):
        return self.lengths.__len__()

    def __getitem__(self, elem):
        self.file.seek(self.coordinates[elem])
        N = self.lengths[elem]
        return self.proto_class().ParseFromString(self.file.read(N))

    def __iter__(self) -> Iterator[GeneratedProtocolMessageType]:
        for n in range(self.__len__()):
            yield self[n]




